org: gerardosabetta
app: botardo
service: botardo
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    AUTH_CLIENT: ${env:AUTH_CLIENT}

functions:
  blue:
    handler: ./src/blue.handler
    events:
      - http:
          path: blue
          method: any
  oauth:
    handler: ./src/oauth.handler
    events:
      - http:
          path: oauth
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
