org: gerardosabetta
app: botardo
service: botardo
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  environment:
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}

functions:
  blue:
    handler: ./src/blue.handler
    events:
      - http:
          path: blue
          method: any

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
